### ISSUE TITLE
subscribeWith using function variable

### ISSUE THREAD

**Issue by rshah** [ReactiveX/RxKotlin#64]
Hi, i got IllegalArgumentException

```
05-09 13:49:38.811 14734 14734 W System.err: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method b.d.b.k.b, parameter it
05-09 13:49:38.811 14734 14734 W System.err:    at com.myandroid.detail.h$aa$2.a(DetailPresenter.kt)
05-09 13:49:38.811 14734 14734 W System.err:    at com.myandroid.detail.h$aa$2.invoke(DetailPresenter.kt:28)
05-09 13:49:38.811 14734 14734 W System.err:    at e.e.a.a.onNext(subscribers.kt:25)
05-09 13:49:38.811 14734 14734 W System.err:    at e.g.b.onNext(SafeSubscriber.java:139)
05-09 13:49:38.811 14734 14734 W System.err:    at e.d.a.g$2$1.onNext(OnSubscribeRedo.java:249)
05-09 13:49:38.811 14734 14734 W System.err:    at e.d.a.p$a.call(OperatorObserveOn.java:215)
05-09 13:49:38.811 14734 14734 W System.err:    at e.a.b.b$b.run(LooperScheduler.java:107)
05-09 13:49:38.811 14734 14734 W System.err:    at android.os.Handler.handleCallback(Handler.java:730)
05-09 13:49:38.811 14734 14734 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:92)
05-09 13:49:38.811 14734 14734 W System.err:    at android.os.Looper.loop(Looper.java:137)
05-09 13:49:38.811 14734 14734 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5103)
05-09 13:49:38.811 14734 14734 W System.err:    at java.lang.reflect.Method.invokeNative(Native Method)
05-09 13:49:38.811 14734 14734 W System.err:    at java.lang.reflect.Method.invoke(Method.java:525)
05-09 13:49:38.811 14734 14734 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
05-09 13:49:38.811 14734 14734 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
05-09 13:49:38.818 14734 14734 W System.err:    at dalvik.system.NativeStart.main(Native Method)
```

when using `subscribeWith(subscriber)`

``` Kotlin
private val subscriber : FunctionSubscriberModifier<Unit>.() -> Unit = {
        onStart { viewReference?.get()?.showLoading() }
        onNext {  }
        onError {
            viewReference?.get()?.hideLoading()
            viewReference?.get()?.showError(it)
        }
        onCompleted { viewReference?.get()?.hideLoading() }
    }
```

But not when using it like below:

``` Kotlin
subscribeWith {
        onStart { viewReference?.get()?.showLoading() }
        onNext {  }
        onError {
            viewReference?.get()?.hideLoading()
            viewReference?.get()?.showError(it)
        }
        onCompleted { viewReference?.get()?.hideLoading() }
}
```

How to avoid the exception when using `subscribeWith` with variable to function?
I'm using `subscribeWith` to retrofit Observable<Unit>.

**Comment by rshah** [comment]
Sorry for the noise, seems fixed after fixing the retrofit side, and change `FunctionSubscriberModifier<Unit>` to `FunctionSubscriberModifier<Unit?>`
